### PR TITLE
README.md (New Website) (Third Update)

### PR DESCRIPTION
**Pull request by bfdifan1**
We added a new website. You will be asking? We already have FNAF 2. But we found another one with cheats so you can play the normal one or the one with the cheats.

### CODE REVIEW

**Comment by bfdifan1** [comment]
I'm gonna fix this rq don't decline

**Comment by irv77** [comment]
I have chosen the one without cheats for a reason since it ruins the experience of the game.

**Comment by bfdifan1** [comment]
oh that's okay

**Comment by bfdifan1** [comment]
I wont and I'm gonna close it

**Pull request closed without merging**
